language: php

php:
    - 5.5
    - 5.6
    - hhvm
    - nightly

allow_failures:
  matrix:
    php: nightly

sudo: false

cache:
  directories:
  - vendor

before_script:
    - composer install
    - mkdir -p build/logs

script:
    - phpunit

after_script:
    - vendor/bin/coveralls

notifications:
  email: false