language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

dist: trusty
sudo: required

cache:
  directories:
  - vendor

before_script:
  - if ! ([ "$TRAVIS_PHP_VERSION" -eq "71" ] || [ "$TRAVIS_PHP_VERSION" -eq "72" ] || [ "$TRAVIS_PHP_VERSION" -eq "73" ] || [ "$TRAVIS_PHP_VERSION" -eq "74" ]); then composer remove phpstan/phpstan; fi
  - composer install
  - mkdir -p build/logs

script:
  - if [ "$TRAVIS_PHP_VERSION" -eq "71" ] || [ "$TRAVIS_PHP_VERSION" -eq "72" ] || [ "$TRAVIS_PHP_VERSION" -eq "73" ] || [ "$TRAVIS_PHP_VERSION" -eq "74" ]; then vendor/bin/phpstan analyse --memory-limit=-1 --no-progress; fi
  - vendor/bin/phpunit

after_script:
  - vendor/bin/php-coveralls

notifications:
  email: false
