language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm

dist: trusty
sudo: required

cache:
  directories:
  - vendor

before_script:
    - composer install
    - mkdir -p build/logs

script:
  - vendor/bin/phpunit

after_script:
    - vendor/bin/coveralls

notifications:
  email: false
