language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
  - '8.0'

os: linux
dist: trusty

jobs:
  allow_failures:
    - php: 8.0

cache:
  directories:
  - vendor

before_script:
  # Downgrade xdebug to v2 on php 7.3
  - if [ "$TRAVIS_PHP_VERSION" -eq "7.3" ]; then pecl install xdebug-2.9.8; fi
  # PHPStan is only supported on 7.1+
  - if ! ([ "$TRAVIS_PHP_VERSION" -eq "7.1" ] || [ "$TRAVIS_PHP_VERSION" -eq "7.2" ] || [ "$TRAVIS_PHP_VERSION" -eq "7.3" ] || [ "$TRAVIS_PHP_VERSION" -eq "7.4" ]); then composer remove phpstan/phpstan --dev; fi
  - composer install
  - mkdir -p build/logs

script:
  - if [ "$TRAVIS_PHP_VERSION" -eq "7.1" ] || [ "$TRAVIS_PHP_VERSION" -eq "7.2" ] || [ "$TRAVIS_PHP_VERSION" -eq "7.3" ] || [ "$TRAVIS_PHP_VERSION" -eq "7.4" ]; then vendor/bin/phpstan analyse --memory-limit=-1 --no-progress; fi
  - vendor/bin/phpunit

after_script:
  - vendor/bin/php-coveralls

notifications:
  email: false
