name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - '8.0'
          - '8.1'
          - '8.2'
          - '8.3'
          - '8.4'
          - '8.5'
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: gd,mailparse,mbstring,redis

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          composer remove --dev phpstan/phpstan
          composer require --dev -W "phpunit/phpunit:^9"
          composer install --prefer-dist --no-progress --no-interaction --no-scripts
          mkdir -p build/logs

      - name: PHPUnit
        run: |
          vendor/bin/phpunit

      - name: Upload coverage results to Coveralls
        if: ${{ github.event_name == 'push' && matrix.php-version == '8.5' }}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        continue-on-error: true
        run: |
          composer global require php-coveralls/php-coveralls
          php-coveralls --coverage_clover=build/logs/clover.xml -v

  phpstan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - '8.5'
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: gd,mailparse,mbstring,redis

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress --no-interaction --no-scripts
          mkdir -p build/logs

      - name: PHPStan
        run: |
          vendor/bin/phpstan analyse --memory-limit=-1 --no-progress
