name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - '5.5'
          - '5.6'
          - '7.0'
          - '7.1'
          - '7.2'
          - '7.3'
          - '7.4'
          - '8.0'
          - '8.1'
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: gd,mailparse,mbstring,redis

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          # PHPUnit 4 for PHP 5
          if [ "${{ matrix.php-version }}" == "5.5" ] || [ "${{ matrix.php-version }}" == "5.6" ]; then composer require phpunit/phpunit:^4; fi
          # PHPUnit 6 for PHP 7.0 - 7.2
          if [ "${{ matrix.php-version }}" == "7.0" ] || [ "${{ matrix.php-version }}" == "7.1" ] || [ "${{ matrix.php-version }}" == "7.12 ]; then composer require phpunit/phpunit:^6; fi
          # PHPUnit 9 for 7.3+
          if [ "${{ matrix.php-version }}" == "7.3" ] || [ "${{ matrix.php-version }}" == "7.4" ] || [ "${{ matrix.php-version }}" == "8.0" ] || [ "${{ matrix.php-version }}" == "8.1" ]; then composer require phpunit/phpunit:^9; fi
          # PHPStan is only supported on 7.1+
          if [ "${{ matrix.php-version }}" == "5.5" ] || [ "${{ matrix.php-version }}" == "5.6" ] || [ "${{ matrix.php-version }}" == "7.0" ]; then composer remove phpstan/phpstan; fi
          # Only report coverage on 7.4
          if [ "${{ matrix.php-version }}" == "7.4" ]; then composer require php-coveralls/php-coveralls; fi
          composer install --prefer-dist --no-progress --no-interaction --no-scripts
          mkdir -p build/logs

      - name: PHPUnit
        run: |
          vendor/bin/phpunit

      - name: PHPStan
        run: |
          # PHPStan is only supported on 7.1+
          if ! ([ "${{ matrix.php-version }}" == "5.5" ] || [ "${{ matrix.php-version }}" == "5.6" ] || [ "${{ matrix.php-version }}" == "7.0" ]); then vendor/bin/phpstan analyse --memory-limit=-1 --no-progress; fi

      - name: Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          # Only report on 7.4
          if [ "${{ matrix.php-version }}" == "7.4" ]; then vendor/bin/php-coveralls; fi
